name: NPCManager
version: 0.1
main: moe.txacg.npcmanager.NPCManager
description: "Multifunction NPC management tools."
author: Txacg
website: "https://github.com/txacg/NPCManager"

commands:
  npcmanager:
    description: The command for NPCManager
    aliases: nm
    permission: nm.command
    permission-message: "You do not have the required permission: <permission>"
    useage: /<command>