name: NPCManager
version: 0.1
main: moe.txacg.npcmanager.NPCManager
description: "Multifunction NPC management tools."
author: Txacg
website: "https://github.com/txacg/NPCManager"

commands:
  npcmanager:
    description: The command for NPCManager
    aliases: nm
    permission: nm.command
    permission-message: "You do not have the required permission: <permission>"
    useage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  nm.command:
    description: Base permission node for commands
    default: true
  nm.spawn:
    description:
    default: op
  nm.info:
    description:
    default: op
  nm.remove:
    description:
    default: op
  nm.edit.add:
    description:
    default: op
  nm.edit.del:
    description:
    default: op
  nm.me.spawn:
    description: Spawn player's player NPC
    default: true
  nm.me.remove:
    description: Remove player's player NPC
    default: true
  nm.import:
    description: Import Shopkeeper's save.yml and save to database
    default: op
  nm.reload:
    description: Reload permission
    default: op
  nm.version:
    description: View plugin version
    default: true